# Generated by Django 2.1 on 2018-08-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('publish_date', models.CharField(max_length=40)),
                ('visit_date', models.CharField(max_length=40)),
                ('article_url', models.TextField()),
            ],
            options={
                'db_table': 'articleTable',
            },
        ),
    ]
